services:
  - type: web
    name: sistema-admin-ai
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /api/health
    envVars:
      - key: API_BASE_URL
        value: http://localhost/Sistema_Administracion-topsecret/SistemaAdmin
      - key: API_KEY
        value: sistema_admin_ai_2024_secure_key
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
